In [28]:
import pandas as pd
import numpy as np

In [3]:
evict = pd.read_csv('../data/evictMerge.csv')

In [6]:
evict = evict.loc[evict.year == 2016]

In [13]:
ward8 = [set([11001007301, 11001007401, 11001007601, 11001007503, 
         11001007504, 11001007502, 11001007408, 11001007403, 
         11001007409, 11001007304, 11001009804, 11001009700, 
         11001009801, 11001009802, 11001009811, 11001009810, 
         11001010900, 11001009807, 11001007301, 11001009802, 
         11001009801, 11001009803, 11001009700, 11001010400, 
         11001007304, 11001007409, 11001007403, 11001007404, 
         11001007406, 11001007408, 11001007502, 11001007407,
         11001007406, 11001007401, 11001007503, 11001007504, 
         11001007502, 11001007601])]

In [22]:
ward8df = evict.loc[(evict.GEOID == 11001007301) | 
          (evict.GEOID == 11001007304) |
          (evict.GEOID == 11001007401) | 
          (evict.GEOID == 11001007403) | 
          (evict.GEOID == 11001007404) |
          (evict.GEOID == 11001007406) |
          (evict.GEOID == 11001007407) |
          (evict.GEOID == 11001007408) |
          (evict.GEOID == 11001007409) |
          (evict.GEOID == 11001007502) |
          (evict.GEOID == 11001007503) |
          (evict.GEOID == 11001007504) |
          (evict.GEOID == 11001007601) |
          (evict.GEOID == 11001009700) |
          (evict.GEOID == 11001009801) |
          (evict.GEOID == 11001009802) |
          (evict.GEOID == 11001009803) |
          (evict.GEOID == 11001009804) |
          (evict.GEOID == 11001009807) |
          (evict.GEOID == 11001009810) |
          (evict.GEOID == 11001009811) |
          (evict.GEOID == 11001010400) |
          (evict.GEOID == 11001010900)]

In [23]:
puds = pd.read_csv('../data/OpenData/Planned_Unit_Development_PUDs.csv')

In [56]:
ward8puds2 = puds.loc[(puds.OBJECTID == 66488) |
                     (puds.OBJECTID == 66490) |
                     (puds.OBJECTID == 66368) |
                     (puds.OBJECTID == 66502) |
                     (puds.OBJECTID == 66478)]

In [57]:
ward8puds2['GEOID'] = np.nan

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [62]:
ward8puds2['GEOID'].loc[ward8puds2.OBJECTID == 66478] = 11001009807

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [67]:
ward8pudsdf = pd.concat([ward8puds, ward8puds2])

In [75]:
ward8pudsdf.count()

OBJECTID                22
PUD_NAME                22
PUD_WEB_URL             22
PUD_CHANGE_NARRATIVE    22
PUD_ZONING              22
PUD_STATUS              22
PUD_CASE_NUMBER         22
SHAPEAREA               22
SHAPELEN                22
GLOBALID                22
WARD                    22
GEOID                   22
dtype: int64

In [72]:
ward8df2 = ward8df.merge(ward8pudsdf, on='GEOID', how='outer')

In [86]:
ward8df2[['GEOID', 'pct-white','poverty-rate', 'renter-occupied-households']]

          GEOID  pct-white  poverty-rate  renter-occupied-households
0   11001007301      61.02          3.29                      1021.0
1   11001007304       3.47         38.02                       974.0
2   11001007401       0.20         58.38                       761.0
3   11001007401       0.20         58.38                       761.0
4   11001007403       1.23         26.65                       968.0
5   11001007404       0.71         38.26                       949.0
6   11001007406       0.00         28.96                       946.0
7   11001007407       0.84         24.35                       833.0
8   11001007407       0.84         24.35                       833.0
9   11001007408       0.85         45.09                       916.0
10  11001007409       0.66         35.70                      1152.0
11  11001007502       1.04         48.96                      1412.0
12  11001007503       1.45         44.82                       621.0
13  11001007503       1.45         44.82                       621.0
14  11001007503       1.45         44.82                       621.0
15  11001007504       0.50         48.31                       834.0
16  11001007601       2.25         28.26                      1217.0
17  11001009700       0.27         35.43                       771.0
18  11001009700       0.27         35.43                       771.0
19  11001009700       0.27         35.43                       771.0
20  11001009801       1.02         38.86                       492.0
21  11001009802       0.18         49.48                       474.0
22  11001009803       0.22         43.05                      1088.0
23  11001009804       1.22         33.39                       636.0
24  11001009807       1.91         32.16                       824.0
25  11001009810       0.00         39.74                      1083.0
26  11001009811       0.00         32.40                      1562.0
27  11001010400       7.04         26.32                      1109.0
28  11001010400       7.04         26.32                      1109.0
29  11001010900       1.45         39.42                      1087.0